[2024-11-26T08:49:34.195+0000] {processor.py:161} INFO - Started process (PID=3502) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:49:34.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:49:34.197+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:49:34.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:49:34.199+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:49:34.198+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 24, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:49:34.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:49:34.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.020 seconds
[2024-11-26T08:50:04.563+0000] {processor.py:161} INFO - Started process (PID=3514) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:04.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:50:04.564+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:04.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:04.566+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:04.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 24, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:50:04.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:04.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.034 seconds
[2024-11-26T08:50:07.581+0000] {processor.py:161} INFO - Started process (PID=3515) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:07.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:50:07.583+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:07.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:07.585+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:07.585+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:50:07.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:07.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.026 seconds
[2024-11-26T08:50:37.983+0000] {processor.py:161} INFO - Started process (PID=3527) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:37.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:50:37.985+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:37.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:37.987+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:50:37.986+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:50:37.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:50:38.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.026 seconds
[2024-11-26T08:51:04.387+0000] {processor.py:161} INFO - Started process (PID=3539) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:04.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:51:04.406+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:04.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:04.408+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:04.408+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:51:04.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:04.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.044 seconds
[2024-11-26T08:51:34.792+0000] {processor.py:161} INFO - Started process (PID=3551) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:34.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:51:34.793+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:34.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:34.796+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:51:34.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:51:34.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:51:34.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.021 seconds
[2024-11-26T08:52:05.171+0000] {processor.py:161} INFO - Started process (PID=3563) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:05.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:52:05.186+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:05.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:05.188+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:05.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:52:05.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:05.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.104 seconds
[2024-11-26T08:52:35.536+0000] {processor.py:161} INFO - Started process (PID=3575) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:35.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:52:35.537+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:35.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:35.539+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:52:35.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:52:35.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:52:35.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.050 seconds
[2024-11-26T08:53:05.950+0000] {processor.py:161} INFO - Started process (PID=3587) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:05.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:53:05.952+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:05.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:05.954+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:05.953+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 21, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:53:05.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:05.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.028 seconds
[2024-11-26T08:53:35.325+0000] {processor.py:161} INFO - Started process (PID=3599) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:35.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:53:35.327+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:35.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:35.329+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:53:35.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:53:35.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:53:35.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.048 seconds
[2024-11-26T08:54:05.738+0000] {processor.py:161} INFO - Started process (PID=3611) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:05.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:54:05.759+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:54:05.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:05.761+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:54:05.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:54:05.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:05.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.054 seconds
[2024-11-26T08:54:35.941+0000] {processor.py:161} INFO - Started process (PID=3624) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:35.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:54:35.943+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:54:35.942+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:35.945+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:54:35.944+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:54:35.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:54:35.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.031 seconds
[2024-11-26T08:55:06.107+0000] {processor.py:161} INFO - Started process (PID=3635) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:55:06.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:55:06.118+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:55:06.118+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:55:06.120+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:55:06.119+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:55:06.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:55:06.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.034 seconds
[2024-11-26T08:55:36.309+0000] {processor.py:161} INFO - Started process (PID=3648) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:55:36.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:55:36.310+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:55:36.310+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:55:36.312+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:55:36.312+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:55:36.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:55:36.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.032 seconds
[2024-11-26T08:56:06.508+0000] {processor.py:161} INFO - Started process (PID=3661) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:56:06.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T08:56:06.518+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:56:06.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:56:06.520+0000] {logging_mixin.py:188} INFO - [2024-11-26T08:56:06.519+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T08:56:06.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T08:56:06.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.033 seconds
[2024-11-26T13:17:27.721+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:17:27.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:17:27.734+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:17:27.734+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:17:27.736+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:17:27.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:17:27.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:17:27.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.048 seconds
[2024-11-26T13:17:58.399+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:17:58.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:17:58.409+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:17:58.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:17:58.410+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:17:58.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:17:58.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:17:58.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.034 seconds
[2024-11-26T13:18:28.917+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:18:28.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:18:28.918+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:18:28.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:18:28.920+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:18:28.919+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:18:28.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:18:28.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.029 seconds
[2024-11-26T13:18:59.433+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:18:59.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:18:59.434+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:18:59.434+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:18:59.436+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:18:59.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:18:59.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:18:59.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.048 seconds
[2024-11-26T13:19:29.926+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:19:29.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:19:29.941+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:19:29.941+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:19:29.943+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:19:29.943+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:19:29.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:19:29.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.036 seconds
[2024-11-26T13:20:00.449+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:20:00.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:20:00.450+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:20:00.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:20:00.452+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:20:00.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:20:00.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:20:00.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.025 seconds
[2024-11-26T13:20:30.960+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:20:30.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:20:30.967+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:20:30.967+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:20:30.969+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:20:30.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:20:30.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:20:30.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.027 seconds
[2024-11-26T13:21:01.483+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:21:01.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:21:01.490+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:21:01.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:21:01.492+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:21:01.491+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:21:01.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:21:01.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.028 seconds
[2024-11-26T13:21:31.999+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:21:32.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:21:32.053+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:21:32.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:21:32.055+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:21:32.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:21:32.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:21:32.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.096 seconds
[2024-11-26T13:22:02.547+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:22:02.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:22:02.587+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:22:02.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:22:02.589+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:22:02.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:22:02.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:22:02.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.071 seconds
[2024-11-26T13:22:33.125+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:22:33.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:22:33.150+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:22:33.150+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:22:33.152+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:22:33.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:22:33.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:22:33.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.098 seconds
[2024-11-26T13:23:03.724+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:03.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:23:03.744+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:23:03.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:03.746+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:23:03.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:23:03.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:03.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.050 seconds
[2024-11-26T13:23:24.213+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:24.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:23:24.216+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:23:24.216+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:24.218+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:23:24.218+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:23:24.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:24.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.025 seconds
[2024-11-26T13:23:54.692+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:54.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:23:54.693+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:23:54.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:54.695+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:23:54.694+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:23:54.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:23:54.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.050 seconds
[2024-11-26T13:24:25.211+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:24:25.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:24:25.262+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:24:25.262+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:24:25.264+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:24:25.263+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:24:25.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:24:25.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.073 seconds
[2024-11-26T13:24:55.680+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:24:55.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:24:55.740+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:24:55.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:24:55.742+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:24:55.741+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:24:55.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:24:55.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.087 seconds
[2024-11-26T13:25:26.153+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:25:26.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:25:26.155+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:25:26.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:25:26.157+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:25:26.156+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:25:26.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:25:26.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.026 seconds
[2024-11-26T13:25:56.614+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:25:56.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:25:56.623+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:25:56.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:25:56.625+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:25:56.625+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:25:56.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:25:56.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.037 seconds
[2024-11-26T13:26:27.490+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:26:27.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:26:27.491+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:26:27.491+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:26:27.493+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:26:27.493+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:26:27.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:26:27.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.045 seconds
[2024-11-26T13:26:58.002+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:26:58.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:26:58.015+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:26:58.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:26:58.017+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:26:58.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:26:58.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:26:58.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.040 seconds
[2024-11-26T13:27:28.562+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:27:28.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:27:28.563+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:27:28.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:27:28.565+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:27:28.564+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:27:28.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:27:28.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.095 seconds
[2024-11-26T13:27:59.455+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:27:59.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:27:59.496+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:27:59.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:27:59.498+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:27:59.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/IntegrationTest_d1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/IntegrationTest_d1.py", line 22, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'shedule_interval'
[2024-11-26T13:27:59.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:27:59.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.069 seconds
[2024-11-26T13:28:00.464+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:28:00.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:28:00.466+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:28:00.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:28:00.473+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:28:00.480+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:28:00.480+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:28:00.493+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:28:00.493+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2023-01-01 15:00:00+00:00, run_after=2023-01-08 15:00:00+00:00
[2024-11-26T13:28:00.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.061 seconds
[2024-11-26T13:28:30.991+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:28:30.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:28:30.993+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:28:30.993+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:28:30.999+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:28:31.066+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:28:31.066+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:28:31.078+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:28:31.078+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2023-01-01 15:00:00+00:00, run_after=2023-01-08 15:00:00+00:00
[2024-11-26T13:28:31.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.109 seconds
[2024-11-26T13:29:01.524+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:01.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:29:01.526+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:01.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:01.532+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:01.548+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:01.548+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:29:01.561+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:01.561+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2023-01-01 15:00:00+00:00, run_after=2023-01-08 15:00:00+00:00
[2024-11-26T13:29:01.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.060 seconds
[2024-11-26T13:29:23.174+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:23.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:29:23.184+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:23.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:23.191+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:23.198+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:23.197+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:29:23.211+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:23.211+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:29:23.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.055 seconds
[2024-11-26T13:29:32.213+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:32.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:29:32.214+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:32.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:32.221+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:29:32.229+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:32.229+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:29:32.242+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:29:32.242+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:29:32.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.045 seconds
[2024-11-26T13:30:02.846+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:30:02.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:30:02.858+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:30:02.858+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:30:02.864+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:30:02.872+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:30:02.871+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:30:02.885+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:30:02.885+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:30:02.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.056 seconds
[2024-11-26T13:30:32.973+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:30:32.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:30:32.974+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:30:32.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:30:32.981+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:30:33.048+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:30:33.048+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:30:33.061+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:30:33.060+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:30:33.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.110 seconds
[2024-11-26T13:31:03.439+0000] {processor.py:161} INFO - Started process (PID=425) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:31:03.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:31:03.450+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:31:03.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:31:03.457+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:31:03.472+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:31:03.472+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:31:03.485+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:31:03.485+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:31:03.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.066 seconds
[2024-11-26T13:31:33.973+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:31:33.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:31:33.975+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:31:33.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:31:33.981+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:31:33.997+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:31:33.996+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:31:34.010+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:31:34.009+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:31:34.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.055 seconds
[2024-11-26T13:32:04.502+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:32:04.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:32:04.536+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:32:04.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:32:04.543+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:32:04.559+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:32:04.558+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:32:04.572+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:32:04.572+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:32:04.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.090 seconds
[2024-11-26T13:32:35.073+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:32:35.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:32:35.074+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:32:35.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:32:35.081+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:32:35.097+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:32:35.097+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:32:35.110+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:32:35.110+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:32:35.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.052 seconds
[2024-11-26T13:33:05.605+0000] {processor.py:161} INFO - Started process (PID=477) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:33:05.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:33:05.611+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:33:05.611+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:33:05.618+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:33:05.634+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:33:05.634+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:33:05.648+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:33:05.648+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:33:05.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.064 seconds
[2024-11-26T13:33:36.147+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:33:36.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:33:36.149+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:33:36.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:33:36.155+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:33:36.171+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:33:36.171+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:33:36.183+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:33:36.183+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:33:36.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.054 seconds
[2024-11-26T13:34:06.678+0000] {processor.py:161} INFO - Started process (PID=503) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:34:06.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:34:06.688+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:34:06.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:34:06.694+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:34:06.710+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:34:06.710+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:34:06.722+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:34:06.722+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:34:06.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.067 seconds
[2024-11-26T13:34:37.156+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:34:37.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:34:37.158+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:34:37.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:34:37.164+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:34:37.179+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:34:37.179+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:34:37.192+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:34:37.192+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:34:37.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.050 seconds
[2024-11-26T13:35:07.681+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:35:07.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:35:07.769+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:35:07.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:35:07.775+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:35:07.796+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:35:07.795+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:35:07.815+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:35:07.815+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:35:07.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.159 seconds
[2024-11-26T13:35:38.228+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:35:38.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:35:38.229+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:35:38.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:35:38.236+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:35:38.251+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:35:38.251+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:35:38.264+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:35:38.264+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:35:38.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.055 seconds
[2024-11-26T13:36:08.760+0000] {processor.py:161} INFO - Started process (PID=555) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:36:08.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:36:08.764+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:36:08.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:36:08.770+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:36:08.786+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:36:08.786+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:36:08.799+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:36:08.798+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:36:08.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.056 seconds
[2024-11-26T13:36:39.284+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:36:39.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:36:39.285+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:36:39.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:36:39.291+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:36:39.307+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:36:39.307+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:36:39.320+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:36:39.320+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:36:39.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.109 seconds
[2024-11-26T13:37:09.815+0000] {processor.py:161} INFO - Started process (PID=581) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:37:09.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:37:09.826+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:37:09.825+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:37:09.832+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:37:09.847+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:37:09.847+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:37:09.860+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:37:09.860+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:37:09.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.068 seconds
[2024-11-26T13:37:40.364+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:37:40.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:37:40.366+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:37:40.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:37:40.372+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:37:40.387+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:37:40.387+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:37:40.400+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:37:40.400+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:37:40.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.053 seconds
[2024-11-26T13:38:10.886+0000] {processor.py:161} INFO - Started process (PID=607) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:38:10.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:38:10.912+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:38:10.912+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:38:10.919+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:38:10.935+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:38:10.935+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:38:10.948+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:38:10.948+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:38:10.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.084 seconds
[2024-11-26T13:38:41.425+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:38:41.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:38:41.427+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:38:41.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:38:41.433+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:38:41.449+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:38:41.449+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:38:41.461+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:38:41.461+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:38:41.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.058 seconds
[2024-11-26T13:39:11.945+0000] {processor.py:161} INFO - Started process (PID=633) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:39:11.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:39:11.948+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:39:11.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:39:11.954+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:39:11.970+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:39:11.970+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:39:11.984+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:39:11.983+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:39:12.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.062 seconds
[2024-11-26T13:39:42.486+0000] {processor.py:161} INFO - Started process (PID=646) to work on /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:39:42.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/IntegrationTest_d1.py for tasks to queue
[2024-11-26T13:39:42.487+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:39:42.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:39:42.494+0000] {processor.py:840} INFO - DAG(s) 'commidty_pipeline' retrieved from /opt/airflow/dags/IntegrationTest_d1.py
[2024-11-26T13:39:42.509+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:39:42.509+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-11-26T13:39:42.523+0000] {logging_mixin.py:188} INFO - [2024-11-26T13:39:42.522+0000] {dag.py:3954} INFO - Setting next_dagrun for commidty_pipeline to 2024-11-03 15:00:00+00:00, run_after=2024-11-10 15:00:00+00:00
[2024-11-26T13:39:42.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/IntegrationTest_d1.py took 0.053 seconds
